apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: javadoc-stable
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: javadoc-stable
    spec:
      containers:
      - name: javadoc-stable
        image: galasadev/galasa-javadoc-amd64:latest
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - javadoc-stable
              topologyKey: kubernetes.io/hostname

